### ISSUE TITLE
Post Model Refactor

### ISSUE THREAD

**Issue by uptonm** [uptonm/placeholder-title#29]
## The following enhancements need to be made to the post model:
Add the following fields
- [ ] type: String (value should either be "original" or "repost")
- [ ] date: (Date of post, can just be generated in the post request. Should be updated if post is edited with a put request)
- [ ] reposts: [MongoDB ObjectID ref=User] (array of users that reposted the post)
- [ ] likes: [MongoDB ObjectID ref=User] (array of users that liked the post)
- [ ] poster: MongoDB ObjectID ref=User (single user that posted the post, similar to author. This will only be different from author when there is a reposted post. In the case of the repost, author is the OP, and poster is the reposter)

**Comment by ShawnToubeau** [comment]
I can take this on since I'm already working with the Post controller!
